### ISSUE TITLE
Limit display doesn't work

### ISSUE THREAD

**Issue by Ta2Ta2** [OFFLINE-GmbH/oc-random-images-plugin#1]
Hi,

dispute how many items I specify, it always shows all images..

I'm using the default setup, latest cms version.

please assist.

**Comment by tobias-kuendig** [comment]
Add a `dd($this->property('limit'));` before this line:
https://github.com/OFFLINE-GmbH/oc-random-images-plugin/blob/master/components/RandomImages.php#L114

What value is displayed?

Share some code how you have implemented the component on your page.

**Comment by Ta2Ta2** [comment]
Thanks for your prompt response. 

The value displayed dd($this->property('limit')); showed me "1"

Here is how I implement it on my local machine. 

despite what number I add in the limit column, it always shows all photos, even the figure is showing the limit to 1



<figure data-component="OFFLINE\RandomImages\Components\RandomImages" data-inspector-id="inspectorid-55329245976" data-property-limit="1" data-property-sourcepath="/about_images" data-snippet="randomImages">&nbsp;</figure>



![07B96139-BBB8-42C3-8DE7-B51425307F74](https://user-images.githubusercontent.com/322365/66105249-0f0b5200-e5cc-11e9-9f4a-3259ad03df6c.png)

**Comment by Ta2Ta2** [comment]
<figure data-component="OFFLINE\RandomImages\Components\RandomImages" data-inspector-id="inspectorid-55329245976" data-property-limit="1" data-property-sourcepath="/about_images" data-snippet="randomImages">&nbsp;</figure>

**Comment by tobias-kuendig** [comment]
Can you change this line 

https://github.com/OFFLINE-GmbH/oc-random-images-plugin/blob/master/components/RandomImages.php#L115

to this and see if it fixes the problem:

```php
$images = $images->slice(0, (int)$this->property('limit'));
```

**Comment by Ta2Ta2** [comment]
it works now thanks,

However, it works only for static pages and not for CMS pages / content ..etc.

I'm able to embed and see the <figure> values within my content only under StaticPages. For CMS pages nothing is showing...

**Comment by tobias-kuendig** [comment]
The plugin does not care about the type of page you are using. Please share some code otherwise it's hard to help you out here.

**Comment by Ta2Ta2** [comment]
Please ignore my last comment ,all working well now! thanks for your prompt response.
